### ISSUE TITLE
After removing cordova.js due to "Ionic Deploy" - IPhone status bar overlays header (Same in Ionic view)

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#16] opened 2016-07-07 07:42 UTC
The header overlaps and the color of the indicators (time, battery, etc..) change to white.

This only occurs once I remove the cordova.js file. This is necessary for Ionic deploy to work.
I see the same behaviour constantly in "Ionic View" (same in all projects). 

![image](https://cloud.githubusercontent.com/assets/1857466/16609383/77492966-435c-11e6-826b-39d1421a472d.png)

**Comment by dwieeb** [comment] 2016-07-07 15:15
@sagivf I will test this on an iOS device today! It could be a number of different issues and we may need to rope some people in to help.

**Comment by sagivf** [comment] 2016-07-08 16:03
This has something to do with the https://github.com/apache/cordova-plugin-statusbar plugin.
adding `<preference name="StatusBarOverlaysWebView" value="false" /> ` to the config.xml fixed the position issue. 

Still haven't solved the color issue though.
Plus it kind of hacky having to do this due to the Ionic Platform...

**Comment by sagivf** [comment] 2016-07-08 16:19
OK found something else.

Seeing these errors - 

![image](https://cloud.githubusercontent.com/assets/1857466/16694009/ab962b70-4540-11e6-97e7-2fd782b53da4.png)


But when installing the plugin I get a message saying they are already installed.
My guess is that the cordova.js is injected to late, or something like that.

**Comment by dwieeb** [comment] 2016-07-08 16:21
@sagivf We verified this yesterday on our devices, by the way. This may require a plugin update. We should not be injecting `cordova.js` in javascript.

**Comment by sagivf** [comment] 2016-07-08 16:24
You mean you verified that it works? Not sure I follow. Is there a change on the way which will address this? Is there a workaround in the meantime?

**Comment by dwieeb** [comment] 2016-07-08 16:32
Sorry, I meant that we're also getting the status bar issue. I'm looking at our options right now.

**Comment by dwieeb** [comment] 2016-07-11 16:24
@sagivf We will be fixing this issue this week. @Fuiste is looking into fixing the deploy plugin so this no longer happens. Ionic View is also being addressed.

**Comment by Manduro** [comment] 2016-07-14 21:08
This is not only happening for statusbar or splashscreen, but for any cordova plugin. Still, for the statusbar you can use the following config setting to prevent it from overlapping the header:

```ts
const ionicConfig = {
  platforms: {
    ios: {
      statusbarPadding: true
    }
  }
};

ionicBootstrap(App, providers, ionicConfig);
```

**Comment by dwieeb** [comment] 2016-07-15 01:19
@Manduro Yep, the problem is just an order-of-operations issue with how we're loading cordova.js. The status bar is just the most immediate and obvious thing that's broken.

**Comment by Fuiste** [comment] 2016-07-21 00:56
As @Manduro mentioned on the `ionic-plugin-deploy` repo, I'm currently working on a fix for this wherein the reference to `cordova.js` is manipulated natively in the plugin rather than in the cloud client.  It's still not 100% yet, and I still need to add Android support, but this should be addressed in the coming days.

**Comment by joshgarwood** [comment] 2016-08-12 20:42
@Fuiste any update on the fix for this and when it will be generally available?  Thanks for knocking this out, by the way!

**Comment by Fuiste** [comment] 2016-08-12 20:44
Oh, forgot to mention this, but the plugin v`0.6.0` was released yesterday, which addresses this problem.

You should no longer need to remove the `cordova.js` reference now, so feel free to give it a spin!

**Comment by dwieeb** [comment] 2016-08-13 00:31
Next week I will be testing and prepping the cloud client with the new version of the deploy plugin. 

This should be resolved soon so we can get this stuff out the door!

**Comment by dwieeb** [comment] 2016-08-18 04:30
@sagivf @joshgarwood @Manduro If you update to the latest cloud client and deploy plugin, this issue should be fixed. Remember to add the `cordova.js` reference back in your `index.html`.

Let me know how it goes!

**Comment by joshgarwood** [comment] 2016-08-18 04:36
Thanks @dwieeb !!  I recently upgrade to Ionic 2 Beta 11, and there's a peer dependency issue with Angular RC.4.  I noticed the Issue created [here](https://github.com/driftyco/ionic-cloud-angular/issues/9), so unfortunately I don't think I can upgrade cloud angular until that issue is resolved.

**Comment by dwieeb** [comment] 2016-08-18 04:39
@joshgarwood Okay, cool. I'm planning on another release tomorrow that should clear that issue up.

**Closed** 2016-08-19 16:38 UTC
Labels: bug

**Comment by sagivf** [comment] 2016-08-21 11:56
thanks @dwieeb works nicely!
