### ISSUE TITLE
Password Reset No Longer works 

### ISSUE THREAD

**Issue by ycuevas21** [driftyco/ionic-cloud#86] opened 2016-11-03 18:13 UTC
Problem: requestPasswordReset method does not
I believe it has to do with local storage. I get this error
![screen shot 2016-11-03 at 10 56 48 am](https://cloud.githubusercontent.com/assets/13423770/19979039/342c2382-a1b6-11e6-9813-90717b1295e8.png)
I believe it is coming from the set method in requestPasswordReset.
![screen shot 2016-11-03 at 11 12 40 am](https://cloud.githubusercontent.com/assets/13423770/19979116/83a69410-a1b6-11e6-8709-968b8e22456a.png)

**Comment by bgizdov** [comment] 2016-11-14 15:51
Yes I have the same issue, still no solution or reply
https://github.com/driftyco/ionic-cloud/issues/81

**Comment by dwieeb** [comment] 2016-11-14 16:12
Happening in a file called `polyfills.js`?

**Comment by ramoncarreras** [comment] 2016-11-18 13:02
Same problem here.

**Comment by RandyLedbetter** [comment] 2016-11-20 17:26
I, too, am experiencing the same error as originally reported by **ycuevas21** 17 days ago. In my case, the error is happening when making the request from a local dev machine in a desktop browser. I do not have the stack traces for the failure in the Android emulator, but Auth.requestPasswordReset(email:string) is not functioning there either.

There is very limited documentation on how to best implement this feature, but I am simply taking an email address submitted via a form and calling this.auth.requestResetPassword(this.form.email), where this.auth is Auth imported from '@ionic/cloud-angular'.

![image](https://cloud.githubusercontent.com/assets/2808167/20464713/62abc606-af01-11e6-8c08-e08ef7bc7e11.png)

**Comment by ericb** [comment] 2016-11-22 14:56
Duplicate of #81, please follow progress there.

**Closed by ericb** 2016-11-22 14:56 UTC
